import { CoinListItem, getCoinList } from "@coin-view";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage<{ data: CoinListItem[] }> = (props) => {
  const [data, setData] = React.useState<CoinListItem[]>([]);

  React.useEffect(() => {
    setData(props.data);
  }, [props.data]);

  console.log({ data });

  const refreshList = React.useCallback(async () => {
    const res = await fetch("/api/list");
    const {data: newData} = await res.json();
    setData(newData);
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Coin View</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Coin View</h1>
        <button onClick={refreshList}>Refresh</button>
        {data?.map((item) => (
          <p key={item.id}>
            {item.name} {item.quote.USD.price.toFixed(4)}$
          </p>
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export async function getServerSideProps() {
  // Fetch data from external API
  const { data } = await getCoinList();

  // Pass data to the page via props
  return { props: { data } };
}

export default Home;
