name: Build
on: push

jobs:
  build:
    name: Build production
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Checkout
        uses: actions/checkout@v2

      - name: Clean Install
        run: npm ci

      - name: Building
        run: npm run build
