name: Build
on: push

jobs:
  build:
    name: Build production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Clean Install
        run: npm ci

      - name: Linting
        run: npm run build
