name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build production
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: v18.12.1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean Install
        run: npm ci

      - name: Building
        run: npm run build
